coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        informational: true

ignore:
  - "**/*.d.ts"
  - "**/types.ts"
  - "**/schema.ts"
  - "**/*.astro"
  - "src/const/**"
  - "src/data/**"
  - "src/tests/**"
