[[plugins]]
package = 'netlify-plugin-gatsby-cache'

[[plugins]]
package = '@algolia/netlify-plugin-crawler'

[[plugins]]
package = '@netlify/plugin-lighthouse'

[[plugins]]
package = 'netlify-plugin-inline-critical-css'

[[plugins]]
package = 'netlify-plugin-image-optim'

[[plugins]]
package = 'netlify-plugin-submit-sitemap'
