[[plugins]]
package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "netlify-plugin-minify-html"
[plugins.inputs]
contexts = ['production', 'branch-deploy', 'deploy-preview']
[plugins.inputs.minifierOptions]
removeComments = true

[[plugins]]
package = 'netlify-plugin-gatsby-cache'

[[plugins]]
package = '@algolia/netlify-plugin-crawler'

[[plugins]]
package = 'netlify-plugin-inline-critical-css'

[[plugins]]
package = 'netlify-plugin-image-optim'

[[plugins]]
package = 'netlify-plugin-submit-sitemap'

[[plugins]]
package = '@netlify/plugin-lighthouse'