packages:
  - ./
overrides:
  chokidar: ">=5.0.0"
  semver: ">=7.0.0"
  tinyexec: "1.1.2"
allowBuilds:
  "@astrojs/compiler-rs": true
  "@biomejs/biome": true
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAge: 4320 # 3 days
trustPolicy: "no-downgrade"
blockExoticSubdeps: true
