packages:
  - ./
allowBuilds:
  "@astrojs/compiler-rs": true
  "@biomejs/biome": true
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAge: 4320 # 3 days
blockExoticSubdeps: true
minimumReleaseAgeExclude:
  # Renovate security update: pnpm@11.8.0
  - pnpm@11.8.0
