packages:
  - ./
allowBuilds:
  "@astrojs/compiler-rs": true
  "@biomejs/biome": true
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAge: 4320 # 3 days
trustPolicy: "no-downgrade"
blockExoticSubdeps: true
