name = "biancafiore"
main = "dist/_worker.js/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2026-03-12"

[assets]
directory = "dist"
binding = "ASSETS"

[env.development]
name = "biancafiore-development"

[env.production]
name = "biancafiore"

[[env.production.routes]]
pattern = "biancafiore.me/*"
zone_name = "biancafiore.me"
