backend:
  name: github
  repo: fbuireu/biancafiore
  branch: master
  commit_messages:
    create: '{{collection}} "{{slug}}" created'
    update: '{{collection}} "{{slug}}" updated'
    delete: '{{collection}} "{{slug}}" deleted'
    uploadMedia: '[skip ci] {{path}} media uploaded'
    deleteMedia: '[skip ci] {{path}} media deleted'
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow
site_url: https://biancafiore.me
display_url: https://biancafiore.me
logo_url: https://biancafiore.me/images/logo.svg
collections:
  - name: locales
    label: Locales
    label_singular: Locale
    identifier_field: name
    folder: src/locales
    description: A list of all availables locales. They will appear on article creation page
    create: true
    editor:
      preview: false
    fields:
      - { name: name, label: Name, required: true, widget: string }
      - { name: iso, label: ISO code, required: true, widget: string, pattern: ['^[a-z]{2}$', 'This field must have only 2 characters']}
  - name: menu
    label: Menu
    label_singular: Menu element
    folder: site/menu
    description: A list of all menu items
    create: true
    editor:
      preview: false
    fields:
      - { name: name, label: Name, widget: string }
      - { name: slug, label: Slug, widget: string }
  - name: tags
    label: Tags
    label_singular: Tag
    identifier_field: tag
    folder: src/articles/tags
    description: A list of all created tags. They will appear on article creation page
    create: true
    editor:
      preview: false
    fields:
      - { name: templateKey, label: Template Key, required: true, default: tags, widget: hidden }
      - { name: tag, label: Tag, widget: string }
  - name: articles
    label: Articles
    label_singular: Article
    identifier_field: content.title
    folder: src/articles
    description: A list of all created articles
    slug: '{{seo.slug}}'
    create: true
    preview_path: articles/{{slug}}
    show_preview_links: true
    fields:
      - { name: templateKey, label: Template Key, required: true, default: articles, widget: hidden }
      - { name: locale, label: Locale, required: true, widget: relation, collection: locales, searchFields: name, valueField: name, displayFields: name }
      - {name: seo, label: SEO, widget: object,
         fields: [
         { name: metaDescription, label: Meta description, required: true, widget: text },
         { name: author, label: Author, default: Bianca Fiore, required: true, widget: string },
         { name: slug, label: Slug, required: true, widget: string }]}
      - { name: content, label: Content,  widget: object,
          fields:[
          { name: publishDate, label: Publish date, required: true, widget: datetime, dateFormat: MM/DD/YYYY, timeFormat: HH:mm, format: LLL },
          { name: readingTime, label: Reading time, widget: number, valueType: int, min: 0, max: 25 },
          { name: isFeaturedPost, label: Featured Post, required: false, widget: boolean },
          { name: featuredimage, label: Featured Image, required: false, widget: image },
          { name: title, label: Title, required: true, widget: string },
          { name: tags, label: Tags, required: true, widget: relation, collection: tags, searchFields: tag, valueField: tag, displayFields: tag, multiple: true },
          { name: body, label: Body, required: true, widget: markdown }]}
  - name: pages
    label: Pages
    label_singular: Page
    slug: '{{slug}}'
    description: A list of all created pages and its configuration
    create: true
    files:
      - name:  home
        label: Home
        file: src/pages/markdown/index.md
        show_preview_links: true
        fields:
          - { name: title, label: Title, required: true, widget: string }
          - { name: image, label: Image, required: false, widget: image }
          - { name: description, label: Description, widget: string }
          - { name: testimonials, label: Testimonials, widget: list,
              fields: [
              { name: quote, label: Quote,  widget: string },
              { name: author, label: Author, widget: string },
              { name: description, label: Description, widget: string }]}
      - name: about-me
        label: About me
        file: src/pages/markdown/about-me.md
        show_preview_links: true
        fields:
          - { name: title, label: Title, widget: string }
          - { name: slug, label: Slug, required: true, default: about-me, widget: string }
          - { name: body, label: Body, widget: markdown }