backend:
  name: git-gateway
  repo: fbuireu/biancafiore
  branch: master
  commit_messages:
    create: '{{collection}} "{{slug}}" created'
    update: '{{collection}} "{{slug}}" updated'
    delete: '{{collection}} "{{slug}}" deleted'
    uploadMedia: '[skip ci] {{path}} media uploaded'
    deleteMedia: '[skip ci] {{path}} media deleted'
media_folder: static/assets/images
public_folder: /assets/images
publish_mode: editorial_workflow
site_url: https://biancafiore.me
display_url: https://biancafiore.me
logo_url: https://biancafiore.me/images/logo.svg
collections:
  - name: languages
    label: Languages
    description: A list of all availables languages. They will appear on article creation page
    label_singular: Language
    identifier_field: name
    slug: '{{slug}}'
    folder: content/languages
    create: true
    editor:
      preview: false
    fields:
      - {name: key, label: Key, required: true, widget: hidden, default: tag}
      - {name: name, label: Name, required: true, widget: string}
      - {name: isoCode, label: ISO code, required: true, widget: string, pattern: ['^[a-z]{2}$', 'This field must have only 2 characters']}
  - name: menu
    label: Menu
    description: A list of all menu items
    label_singular: Menu element
    identifier_field: name
    folder: content/menu
    create: true
    editor:
      preview: false
    fields:
      - {name: key, label: Key, required: true, widget: hidden, default: menuItem }
      - {name: name, label: Name, required: true, widget: string }
      - { name: slug, label: Slug, required: true, widget: string }
      - { name: position, label: Position, required: true, widget: number, valueType: int,  min: 0 }
  - name: tags
    label: Tags
    label_singular: Tag
    identifier_field: tag
    slug: '{{slug}}'
    folder: content/tags
    description: A list of all created tags. They will appear on article creation page
    create: true
    editor:
      preview: false
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: tag }
      - { name: tag, label: Tag, required: true, widget: string }
  - name: blog
    label: Blog
    description: A list of all created articles
    label_singular: Article
    identifier_field: content.title
    slug: '{{seo.slug}}'
    folder: content/articles
    create: true
    preview_path: blog/{{slug}}
    show_preview_links: true
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: blog }
      - { name: language, label: Language, required: true, widget: relation, collection: languages, searchFields: [name, isoCode], valueField: name, displayFields: name }
      - {name: seo, label: SEO, widget: object,
         fields: [
         { name: metaDescription, label: Meta description, required: true, widget: text },
         { name: author, label: Author, required: true, widget: string, default: Bianca Fiore },
         { name: slug, label: Slug, required: true, widget: string }]}
      - { name: content, label: Content,  widget: object,
          fields: [
          { name: publishDate, label: Publish date, required: false, widget: datetime, default: '', dateFormat: MM/DD/YYYY, timeFormat: HH:mm, format: LLL },
          { name: lastUpdated, label: Last updated, required: false, widget: datetime, default: '', dateFormat: MM/DD/YYYY, timeFormat: HH:mm, format: LLL },
          { name: readingTime, label: Reading time, required: false, widget: number, default: '', valueType: int, min: 0, max: 25 },
          { name: isFeaturedPost, label: Featured Post, required: false, widget: boolean },
          { name: featuredImage, label: Featured Image, required: false, widget: image },
          { name: title, label: Title, required: true, widget: string },
          { name: tags, label: Tags, required: false, widget: relation, collection: tags, searchFields: tag, valueField: tag, displayFields: tag, multiple: true }]}
      - { name: body, label: Body, required: true, widget: markdown }
  - name: home
    label: Home
    description: A list of all availables content for home page
    slug: '{{slug}}'
    create: false
    files:
      - name: home-english
        label: Home - English
        file: content/pages/home/index.en.md
        show_preview_links: true
        fields:
          - { name: language, label: language, required: true, widget: hidden, default: en }
          - { name: title, label: Title, required: true, widget: string }
          - { name: image, label: Image, required: false, widget: image }
          - { name: testimonials, label: Testimonials, required: false, widget: list,
              fields: [
              { name: author, label: Author, required: true, widget: string },
              { name: quote, label: Quote, required: true, widget: string },
              { name: description, label: Description, required: false, widget: string }]}
          - { name: body, label: Body, required: true, widget: markdown }
      - name: home-italian
        label: Home - Italian
        file: content/pages/home/index.it.md
        show_preview_links: true
        fields:
          - { name: language, label: language, required: true, widget: hidden, default: it }
          - { name: title, label: Title, required: true, widget: string }
          - { name: image, label: Image, required: false, widget: image }
          - { name: testimonials, label: Testimonials, required: false, widget: list,
              fields: [
              { name: author, label: Author, required: true, widget: string },
              { name: quote, label: Quote, required: true, widget: string },
              { name: description, label: Description, required: false, widget: string }]}
          - { name: body, label: Body, required: true, widget: markdown }
      - name: home-catalan
        label: Home - Catalan
        file: content/pages/home/index.ca.md
        show_preview_links: true
        fields:
          - { name: language, label: language, required: true, widget: hidden, default: ca }
          - { name: title, label: Title, required: true, widget: string }
          - { name: image, label: Image, required: false, widget: image }
          - { name: testimonials, label: Testimonials, required: false, widget: list,
              fields: [
              { name: author, label: Author, required: true, widget: string },
              { name: quote, label: Quote, required: true, widget: string },
              { name: description, label: Description, required: false, widget: string }]}
          - { name: body, label: Body, required: true, widget: markdown }
      - name: home-spanish
        label: Home - Spanish
        file: content/pages/home/index.es.md
        show_preview_links: true
        fields:
          - { name: language, label: language, required: true, widget: hidden, default: es }
          - { name: title, label: Title, required: true, widget: string }
          - { name: image, label: Image, required: false, widget: image }
          - { name: testimonials, label: Testimonials, required: false, widget: list,
              fields: [
              { name: author, label: Author, required: true, widget: string },
              { name: quote, label: Quote, required: true, widget: string },
              { name: description, label: Description, required: false, widget: string }]}
          - { name: body, label: Body, required: true, widget: markdown }
