backend:
  name: github #git-gateway
  repo: fbuireu/biancafiore
  branch: master
  squash_merges: true
  commit_messages:
    create: 'docs(content): {{collection}} "{{slug}}" created'
    update: 'docs(content): {{collection}} "{{slug}}" updated'
    delete: 'docs(content): {{collection}} "{{slug}}" deleted'
    uploadMedia: 'docs: [skip ci] {{path}} media uploaded'
    deleteMedia: '[skip ci] {{path}} media deleted'
    openAuthoring: '{{message}}'
media_folder: static/assets/images
public_folder: /assets/images
publish_mode: editorial_workflow
site_url: https://biancafiore.me
display_url: https://biancafiore.me
logo_url: https://biancafiore.me/images/logo.svg
collections:
  - name: languages
    label: Languages
    label_singular: Language
    description: A list of all availables languages. They will appear on article creation page
    identifier_field: name
    slug: '{{slug}}'
    folder: content/languages
    create: true
    editor:
      preview: false
    sortable_fields: ['name']
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: tag }
      - { name: name, label: Name, required: true, widget: string }
      - { name: isoCode, label: ISO code, required: true, widget: string, pattern: ['^[A-Z]{2}$', 'This field must have only 2 capitalized characters'] }
  - name: menuItems
    label: Menu item
    label_singular: Menu item
    description: A list of all menu items
    identifier_field: name
    folder: content/navigation/menu
    create: true
    editor:
      preview: false
    sortable_fields: ['name', 'position']
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: menuItem }
      - { name: name, label: Name, required: true, widget: string }
      - { name: slug, label: Slug, required: true, widget: string }
      - { name: position, label: Position, required: true, widget: number, valueType: int,  min: 0 }
  - name: socialNetwork
    label: Social Network items
    label_singular: Social Network item
    description: A list of all social network items
    identifier_field: name
    folder: content/navigation/social-networks
    create: true
    editor:
      preview: false
    sortable_fields: [ 'name', 'position' ]
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: socialNetworkItem }
      - { name: name, label: Name, required: true, widget: string }
      - { name: url, label: URL, required: true, widget: string }
      - { name: position, label: Position, required: true, widget: number, valueType: int,  min: 0 }
  - name: tags
    label: Tags
    label_singular: Tag
    description: A list of all created tags. They will appear on article creation page
    identifier_field: name
    slug: '{{slug}}'
    folder: content/tags
    create: true
    editor:
      preview: false
    sortable_fields: ['name']
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: tag }
      - { name: name, label: Name, required: true, widget: string }
  - name: cities
    label: Cities
    label_singular: City
    description: A list of all created cities. They will appear on about me page
    identifier_field: name
    slug: '{{slug}}'
    folder: content/cities
    create: true
    editor:
      preview: true
    sortable_fields: ['name']
    view_filters:
      - { label: Initial City, field: isInitialCity, pattern: true }
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: city }
      - { name: name, label: Name, required: true, widget: string }
      - { name: isInitialCity, label: Initial city, required: false, widget: boolean }
      - { name: countryIsoCode, label: Country ISO code, required: true, widget: string, pattern: ['^[A-Z]{2}$', 'This field must have only 2 capitalized characters'] }
      - { name: coordinates, label: Coordinates, required: true, widget: map }
  - name: authors
    label: Authors
    label_singular: Author
    description: A list of all authors available.
    identifier_field: name
    slug: '{{slug}}'
    folder: content/authors
    create: true
    editor:
      preview: false
    sortable_fields: ['name']
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: tag }
      - { name: name, label: Name, required: true, widget: string }
      - { name: image, label: Image, required: true, widget: image, allow_multiple: false }
      - { name: description, label: Description, required: false, widget: string }
  - name: navigation
    label: Navigation
    label_singular: Navigation
    description: A list of all navigation menus
    identifier_field: name
    folder: content/navigation
    create: true
    editor:
      preview: false
    sortable_fields: ['name']
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: navigation }
      - { name: name, label: Name, required: true, widget: string }
      - { name: menuItems, label: Menu Items, required: true, widget: relation, collection: menuItems, search_fields: [name, slug], value_field: name, display_fields: [name], multiple: true }
      - { name: body, label: Body, required: true, widget: markdown }
  - name: projects
    label: Projects
    label_singular: Project
    description: A list of all created projects
    identifier_field: content.name
    slug: '{{content.name}}'
    folder: content/projects
    create: true
    preview_path: projects/{{slug}}
    show_preview_links: true
    sortable_fields: ['content.name', 'content.publishDate']
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: project }
      - { name: language, label: Language, required: true, widget: relation, collection: languages, search_fields: [name, isoCode], value_field: name, display_fields: [name] }
      - { name: isDraft, label: Draft, required: true, widget: boolean, default: true }
      - { name: content, label: Content,  widget: object, collapsed: true,
          fields: [
            { name: name, label: Name, required: true, widget: string },
            { name: publishDate, label: Publish date, required: false, widget: datetime, date_format: MM/DD/YYYY, time_format: false, format: L },
            { name: featuredImage, label: Featured Image, required: false, widget: image, allow_multiple: false },
            { name: tags, label: Tags, required: false, widget: relation, collection: tags, search_fields: [name], value_field: name, display_fields: [name], multiple: true }] }
      - { name: body, label: Body, required: true, widget: markdown }
  - name: blog
    label: Blog
    label_singular: Article
    description: A list of all created articles
    identifier_field: content.title
    slug: '{{seo.slug}}'
    folder: content/articles
    create: true
    preview_path: blog/{{slug}}
    show_preview_links: true
    sortable_fields: ['content.title', 'content.publishDate', 'content.readingTime']
    view_filters:
      - { label: Draft articles, field: content.isDraft, pattern: true }
      - { label: Featured articles, field: content.isFeaturedArticle, pattern: true }
      - { label: Bianca's articles, field: author,  pattern: 'Bianca' }
      - { label: Emma's articles,field: author, pattern: 'Emma' }
      - { label: Anna's articles, field: author, pattern: 'Anna' }
    view_groups:
      - { label: Featured articles, field: content.isFeaturedArticle }
      - { label: Draft articles, field: content.isDraft }
    fields:
      - { name: key, label: Key, required: true, widget: hidden, default: article }
      - { name: language, label: Language, required: true, widget: relation, collection: languages, search_fields: [name, isoCode], value_field: name, display_fields: [name], default: English }
      - { name: author, label: Author, required: true, widget: relation, collection: authors, search_fields: [name], value_field: name, display_fields: [name], default: Bianca Fiore }
      - { name: isDraft, label: Draft, required: true, widget: boolean, default: true }
      - { name: seo, label: SEO, widget: object, collapsed: true,
          fields: [
            { name: metaDescription, label: Meta description, required: true, widget: text },
            { name: slug, label: Slug, required: true, widget: string }] }
      - { name: content, label: Content,  widget: object, collapsed: true,
          fields: [
            { name: title, label: Title, required: true, widget: string },
            { name: summary, label: Summary, required: false, widget: string },
            { name: publishDate, label: Publish date, required: false, widget: datetime, date_format: MM/DD/YYYY, time_format: false, format: L },
            { name: lastUpdated, label: Last updated, required: false, widget: datetime, date_format: MM/DD/YYYY, time_format: false, format: L },
            { name: readingTime, label: Reading time, required: false, widget: number, value_type: int, min: 0, max: 45 },
            { name: featuredImageLayout, label: Featured Article, required: false, widget: boolean },
            { name: isFeaturedArticle, label: Featured Article, required: false, widget: boolean },
            { name: featuredImage, label: Featured Image, required: false, widget: image, allow_multiple: false },
            { name: tags, label: Tags, required: false, widget: relation, collection: tags, search_fields: [name], value_field: name, display_fields: [name], multiple: true },
            { name: relatedArticlesTitle, label: Related Articles Title, widget: string, default: Related Articles }] }
      - { name: body, label: Body, required: true, widget: markdown }
  - name: pages
    label: Pages
    label_singular: Page
    description: A list of all availables pages
    slug: '{{slug}}'
    create: false
    sortable_fields: []
    files:
      - name: home
        label: Home
        file: content/pages/home.md
        show_preview_links: true
        fields:
          - { name: key, label: Key, required: true, widget: hidden, default: home }
          - { name: title, label: Title, required: true, widget: string }
          - { name: jumbotron, label: Jumbotron, widget: object, collapsed: true,
              fields: [
                { name: welcomeImage, label: Welcome image, required: true, widget: image, allow_multiple: false },
                { name: welcomeTextLeft, label: Welcome text left, required: false, widget: markdown },
                { name: welcomeTextRight, label: Welcome text right, required: false, widget: markdown },
                { name: welcomeDescription, label: Welcome description, required: false, widget: markdown } ] }
          - { name: testimonials, label: Testimonials, widget: object, collapsed: true,
              fields: [
                { name: title, label: Title, required: true, widget: string },
                { name: subtitle, label: Subtitle, required: false, widget: markdown },
                { name: testimonials, label: Testimonials, required: false, label_singular: Testimonial, summary: '{{fields.author}}', add_to_top: true, widget: list,
                  fields: [
                    { name: author, label: Author, required: true, widget: string },
                    { name: quote, label: Quote, required: true, widget: markdown },
                    { name: image, label: Image, required: false, widget: image, allow_multiple: false },
                    { name: description, label: Description, required: false, widget: markdown } ] }] }
          - { name: myWork, label: My Work, widget: object, collapsed: true,
              fields: [
                { name: title, label: Title, required: true, widget: string },
                { name: works, label: Works, required: true,  summary: '{{fields.tags}}', add_to_top: true, widget: list,
                  fields: [
                    { name: tags, label: Tags, required: true, widget: relation, collection: tags, search_fields: [ name ], value_field: name, display_fields: [ name ], multiple: true },
                    { name: image, label: Image, required: true, widget: image, allow_multiple: false } ] }] }
          - { name: latestArticles, label: Latest Articles, widget: object, collapsed: true,
              fields: [
                { name: title, label: Title, required: true, widget: markdown } ] }
          - { name: body, label: Body, required: true, widget: markdown }
      - name: about-me
        label: About me
        file: content/pages/about-me.md
        show_preview_links: true
        fields:
          - { name: key, label: Key, required: true, widget: hidden, default: about-me }
          - { name: jumbotron, label: Jumbotron, widget: object, collapsed: true,
              fields: [
                { name: leftSide, label: Left Side, widget: object, collapsed: true,
                  fields: [
                    { name: title, label: Title, required: true, widget: string },
                    { name: welcomeText, label: Welcome text, required: false, widget: markdown },
                    { name: welcomeDescription, label: Welcome description, required: false, widget: markdown },
                    { name: cta, label: CTA, required: false, widget: string } ] },
                { name: rightSide, label: Right Side, widget: object, collapsed: true,
                  fields: [
                    { name: image, label: Image, required: true, widget: image, allow_multiple: false },
                    { name: socialNetworks, label: Social Networks, required: false, widget: relation, collection: socialNetwork, search_fields: [ name ], value_field: name, display_fields: [ name ], multiple: true }
                  ] } ] }
          - { name: map, label: Map, widget: object, collapsed: true,
              fields: [
                { name: cities, label: Cities, required: true, widget: relation, collection: cities, search_fields: [ name ], value_field: name, display_fields: [ name ], multiple: true }
              ] }
          - { name: timeline, label: Timeline, widget: object, collapsed: true,
              fields: [
                { name: title, label: Title, required: true, widget: string },
                { name: years, label: Years, required: false, label_singular: Year, summary: '{{fields.year}}', add_to_top: true, widget: list,
                  fields: [
                    { name: year, label: Year, required: true, widget: string },
                    { name: city, label: City, required: true, widget: relation, collection: cities, search_fields: [ name ], value_field: name, display_fields: [ name ], multiple: false },
                    { name: image, label: Image, required: true, widget: image, allow_multiple: false },
                    { name: description, label: Description, required: false, widget: markdown } ] }
              ] }
          - { name: latestArticles, label: Latest Articles, widget: object, collapsed: true,
                fields: [
                  { name: title, label: Title, required: true, widget: markdown },
                  { name: quote, label: Quote, required: true, widget: markdown },
                  { name: author, label: Author, required: false, widget: string } ] }
          - { name: body, label: Body, required: true, widget: markdown }
      - name: blog
        label: Blog
        file: content/pages/blog.md
        show_preview_links: true
        fields:
          - { name: key, label: Key, required: true, widget: hidden, default: blog }
          - { name: title, label: Title, required: true, widget: markdown }
          - { name: jumbotron, label: Jumbotron, widget: object, collapsed: true,
              fields: [
                { name: featuredArticle, label: Featured Article, widget: object, collapsed: true,
                  fields: [
                    { name: cta, label: CTA, required: false, widget: string } ] },
                { name: socialNetworks, label: Social Networks, widget: object, collapsed: true,
                  fields: [
                    { name: cta, label: CTA, required: false, widget: string },
                    { name: socialNetworks, label: Social Networks, required: false, widget: relation, collection: socialNetwork, search_fields: [ name ], value_field: name, display_fields: [ name ], multiple: true }
                  ] } ] }
      - name: contact
        label: Contact
        file: content/pages/contact.md
        show_preview_links: true
        fields:
          - { name: key, label: Key, required: true, widget: hidden, default: contact }
          - { name: formInputs, label: Form Inputs, required: false, summary: '{{fields.label}}', allow_add: false, widget: list,
              fields: [
                { name: name, label: Name, required: true, widget: string, pattern: [ '^[a-z]+$', 'This field only accepts lowercase values' ] },
                { name: type, label: Type, required: true, widget: select,
                  options: [
                    { label: 'Hidden', value: 'hidden' },
                    { label: 'Text', value: 'text' },
                    { label: 'Email', value: 'email' },
                    { label: 'Number', value: 'number' },
                    { label: 'Textarea', value: 'textarea' },
                    { label: 'Checkbox', value: 'checkbox' },
                    { label: 'reCAPTCHA', value: 'recaptcha' }] }       ,
                { name: isRequired, label: Required, required: true, widget: boolean },
                { name: label, label: Label, required: true, widget: string },
                { name: value, label: Value, required: false, widget: string },
                { name: isValid, label: isValid, required: true, widget: hidden, default: true },
                { name: errorMessage, label: Error message, required: true, widget: string }] }
          - { name: body, label: Body, required: true, widget: markdown }
