name: 'Prepare Environment'
description: 'Sets up Node.js and pnpm environment'
runs:
  using: "composite"
  steps:
    - name: Validate .nvmrc exists
      shell: bash
      run: |
        if [ ! -f .nvmrc ]; then
          echo "Error: .nvmrc file not found"
          exit 1
        fi

    - name: Use Node.js version from .nvmrc
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: actions/cache@v5
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
