name: Deploy - Production

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [contentful-publish]

permissions:
  contents: read

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: production
      wrangler_env: production
      url: https://biancafiore.me
    secrets: inherit
