name: Deploy - Production

run-name: >-
  ${{ github.event_name == 'repository_dispatch'
      && (github.event.action == 'article-published'
          && format('Article "{0}" published (deploy triggered by Contentful Webhook)', github.event.client_payload.title)
          || format('Article ({0}) unpublished (deploy triggered by Contentful Webhook)', github.event.client_payload.id))
      || 'Deploy to production' }}

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [article-published, article-unpublished]

permissions:
  contents: read

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: production
      wrangler_env: production
      url: https://biancafiore.me
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      GOOGLE_RECAPTCHA_SECRET_KEY: ${{ secrets.GOOGLE_RECAPTCHA_SECRET_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
      CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}
      CONTENTFUL_SIGNIN_TOKEN: ${{ secrets.CONTENTFUL_SIGNIN_TOKEN }}
      ASTRO_DB_REMOTE_URL: ${{ secrets.ASTRO_DB_REMOTE_URL }}
      ASTRO_DB_APP_TOKEN: ${{ secrets.ASTRO_DB_APP_TOKEN }}
