name: E2E Tests
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
env:
  CI: true
  E2E_URL: ${{ github.event_name == 'workflow_dispatch' && vars.E2E_PRODUCTION_URL || vars.E2E_SELF_HOSTED_URL }}
  E2E_COMMAND: ${{ github.event_name == 'workflow_dispatch' && 'yarn test:e2e' || 'yarn test:e2e:changed' }}
jobs:
  e2e-tests:
    name: Run E2E tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare-env.yml
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run E2E Tests
        run: ${{ env.E2E_COMMAND }}
        env:
          CI: ${{ env.CI }}
          E2E_URL: ${{ env.E2E_URL }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
