name: E2E Tests
on:
  workflow_dispatch:
env:
  CI: true
  E2E_URL: ${{ github.event_name == 'workflow_dispatch' && vars.E2E_PRODUCTION_URL || vars.E2E_SELF_HOSTED_URL }}
  E2E_COMMAND: ${{ github.event_name == 'workflow_dispatch' && 'pnpm test:e2e' || 'pnpm test:e2e:changed' }}
jobs:
  end-to-end-tests:
    name: Run E2E tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ./.github/actions/prepare-env
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - name: Run E2E Tests
        run: ${E2E_COMMAND}
        env:
          CI: ${{ env.CI }}
          E2E_URL: ${{ env.E2E_URL }}
      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
