name: 'Prepare Environment'
runs:
  using: "composite"
  steps:
    - name: Use Node.js version from .nvmrc
      id: nvmrc
      shell: bash
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Enable Corepack
      shell: bash
      run: corepack enable
    - name: Get Yarn version from package.json
      id: yarn_version
      shell: bash
      run: |
        YARN_VERSION=$(jq -r '.packageManager' package.json | grep -o 'yarn@[0-9]*\.[0-9]*\.[0-9]*')
        echo "YARN_VERSION=${YARN_VERSION}" >> $GITHUB_ENV
    - name: Install correct Yarn version
      shell: bash
      run: corepack prepare ${{ env.YARN_VERSION }} --activate