name: Release
on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: 'Tag name for the release'
                required: true
    push:
        tags:
            - '*'
    workflow_run:
        workflows: ["E2E Tests", "Unit Tests"]
        types: [completed]
env:
    TAG_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name || github.ref_name }}
jobs:
    check-tag:
        name: Check Tag
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        steps:
            -   name: Check out the repository
                uses: actions/checkout@v4
            -   name: Check if tag exists
                id: check_tag
                run: |
                    git fetch --tags
                    if git rev-parse "${{ env.tag_name }}" >/dev/null 2>&1; then
                      echo "Tag already exists. Cancelling the release."
                      exit 1
    create-release:
        name: Create Release
        runs-on: ubuntu-latest
        needs: check-tag
        steps:
            -   name: Check out the repository
                uses: actions/checkout@v4
            -   name: Create Tag (only for workflow_dispatch)
                if: ${{ github.event_name == 'workflow_dispatch' }}
                run: |
                    git config user.name "github-actions"
                    git config user.email "github-actions@github.com"
                    git tag ${{ env.TAG_NAME }}
                    git push origin ${{ env.TAG_NAME }}
            -   name: Set up GitHub CLI
                run: |
                    sudo apt-get install -y gh
                    echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
            -   name: Create Release with GitHub CLI
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    gh release create ${{ env.TAG_NAME }} --title "Release ${{ env.TAG_NAME }}" --notes "Release notes generated automatically." --generate-notes
