name: Release (manual)

on:
  workflow_dispatch:

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          persist-credentials: false
      - uses: ./.github/actions/prepare-env
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate types
        run: pnpm run sync
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release
      - name: Update major version tag
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          MAJOR_VERSION=$(echo $LATEST_TAG | cut -d. -f1)

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git tag -fa $MAJOR_VERSION -m "Update $MAJOR_VERSION to $LATEST_TAG"

          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git $MAJOR_VERSION --force
