name: Renovate auto-approve
on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
permissions:
  pull-requests: write
jobs:
  approve:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.user.login == 'renovate[bot]' &&
      (contains(github.event.pull_request.labels.*.name, 'patch-update') ||
       contains(github.event.pull_request.labels.*.name, 'minor-update'))
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.PAT }}
