name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  prepare-env:
    uses: ./.github/workflows/prepare-env.yml
  ut-tests:
    needs: prepare-env
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Execute Unit tests
        run: yarn test:ut
