name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ut-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/prepare-env.yml
      - name: Install dependencies
        run: yarn install
      - name: Execute Unit tests
        run: yarn test:ut
